version: '3.8'

services:
  app_dev:
    container_name: vpn_panel_dev
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=vpn_panel
      - JWT_SECRET=your-secret-key
      - JWT_EXPIRATION=3600
    depends_on:
      - postgres
    networks:
      - vpn_network

  # app_prod:
  #   container_name: vpn_panel_prod
  #   build:
  #     context: .
  #     target: production
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_NAME=vpn_panel
  #     - JWT_SECRET=your-secret-key
  #     - JWT_EXPIRATION=3600
  #   depends_on:
  #     - postgres
  #   networks:
  #     - vpn_network

  postgres:
    container_name: vpn_panel_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vpn_panel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vpn_network

volumes:
  postgres_data:

networks:
  vpn_network:
